service: catfacts

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}*"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  subscriptions:
    handler: bin/subscriptions
    events:
      - http:
          path: subscribers
          method: post
  sendfact:
    handler: bin/sendfact
    events:
      - schedule: rate(1 day)
    environment:
      TWILIO_FROM: ${ssm:/twilio_from}
      TWILIO_SID: ${ssm:/twilio_sid~true}
      TWILIO_TOKEN: ${ssm:/twilio_token~true}

resources:
  Resources:
    SubscribersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: contact
            AttributeType: S
        KeySchema:
          - AttributeName: contact
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1