service: catfacts

provider:
  name: aws
  runtime: go1.x
  region: ${opt:region, 'us-west-2'}
  stage: ${opt:stage, 'dev'}
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
      Resource: "arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}*"
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
      Resource: "arn:aws:ssm:${self:provider.region}:*:parameter/twilio/auth"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  authorize:
    handler: bin/authorize

  subscription:
    handler: bin/subscription
    events:
      - http:
          path: /v1/subscription
          method: post
          authorizer:
            name: authorize
            identitySource: method.request.header.Authorization
            type: request

  sendfact:
    handler: bin/sendfact
    events:
      - schedule: rate(1 day)
    environment:
      TWILIO_FROM: ${ssm:/twilio/from}
      TWILIO_SID: ${ssm:/twilio/sid~true}
      TWILIO_TOKEN: ${ssm:/twilio/token~true}

  

resources:
  Resources:
    SubscriptionTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: contact
            AttributeType: S
        KeySchema:
          - AttributeName: contact
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.WWW-Authenticate: "'Basic realm=\"Cat facts\"'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'

